### ISSUE TITLE
Data visualization via vertex shaders

### ISSUE THREAD

**Issue by unimatrixZero1** [mah985/Oculus-3D-Visualization-Tool#7]
- [x] Generate vertex shader data visualization
- [x] methods for assigning CSV columns to axes
- [x] methods for translating and scaling entire dataset
- [x] methods for point highlighting/selection

**Comment by unimatrixZero1** [comment]
If anybody thinks of any useful methods or fields they want exposed, just add them to the list above and I'll implement them tonight.

**Comment by mah985** [comment]
I was thinking initially the user could select the points from a set of 3 drop downs, each corresponding to an axis. The dropdown's could appear when the csv is successfully parsed so that we would have content to populate them with.
Here's a nice tool we could use for live search in the dropdown, something Osgood mentioned he'd like:
[Select2](https://select2.org/)
Take note of [this](https://select2.org/data-sources/arrays) for how to fill a drop down menu from an array. 

Let me know what you think or if you need a hand.

**Comment by unimatrixZero1** [comment]
Sounds reasonable. I might not get the dropdown UI done tonight, but I'll at least have methods for setting the axes.

**Comment by mah985** [comment]
Ill get on the UI right now and let you know when its done

**Comment by seaboyern** [comment]
All features are now implemented and in the system! weeee
